name: WorldStyler
main: muqsit\worldstyler\WorldStyler
api: 3.0.0
version: 1.0

commands:
  /pos1:
    permission: worldstyler.selection
  /pos2:
    permission: worldstyler.selection
  /set:
    permission: worlstyler.set
  /replace:
    permission: worlstyler.replace
  /schem:
    permission: worldstyler.schem
  /copy:
    permission: worldstyler.copy
  /paste:
    permission: worldstyler.paste
  /stack:
    permission: worldstyler.stack

permissions:
  worldstyler:
    default: false
    description: "Grants access to all WorldStyler permissions."
    children:
      selection:
        description: "Grants access to //pos1 and //pos2 commands."
        default: op
      set:
        description: "Grants access to //set command."
        default: op
      replace:
        description: "Grants access to //replace command."
        default: op
      schem:
        description: "Grants access to //schem command."
        default: op
      copy:
        description: "Grants access to //copy command."
        default: op
      paste:
        description: "Grants access to //paste command."
        default: op
      stack:
        description: "Grants access to //stack command."
        default: op
