name: WorldStyler
main: muqsit\worldstyler\WorldStyler
api: 4.0.0
version: 1.0.0

commands:
  /pos1:
    permission: worldstyler.selection
  /pos2:
    permission: worldstyler.selection
  /set:
    permission: worldstyler.set
  /replace:
    permission: worldstyler.replace
  /schem:
    permission: worldstyler.schem
  /copy:
    permission: worldstyler.copy
  /paste:
    permission: worldstyler.paste
  /stack:
    permission: worldstyler.stack
  /fixpcblocks:
    permission: worldstyler.replace

permissions:
  worldstyler:
    default: false
    description: "Grants access to all WorldStyler permissions."
  worldstyler.selection:
    description: "Grants access to //pos1 and //pos2 commands."
    default: op
  worldstyler.set:
    description: "Grants access to //set command."
    default: false
  worldstyler.replace:
    description: "Grants access to //replace command."
    default: false
  worldstyler.schem:
    description: "Grants access to //schem command."
    default: false
  worldstyler.copy:
    description: "Grants access to //copy command."
    default: false
  worldstyler.paste:
    description: "Grants access to //paste command."
    default: false
  worldstyler.stack:
    description: "Grants access to //stack command."
    default: false
