name: WorldStyler
main: muqsit\worldstyler\WorldStyler
api: 4.0.0
version: 1.0.0

commands:
  /pos1:
    permission: worldstyler.selection
  /pos2:
    permission: worldstyler.selection
  /set:
    permission: worldstyler.set
  /replace:
    permission: worldstyler.replace
  /schem:
    permission: worldstyler.schem
  /copy:
    permission: worldstyler.copy
  /paste:
    permission: worldstyler.paste
  /stack:
    permission: worldstyler.stack
  /fixpcblocks:
    permission: worldstyler.replace
  /nice:
      permission: worldstyler.nice

permissions:
  worldstyler:
    default: op
    description: "Grants access to all WorldStyler permissions."
    children:
      worldstyler.selection:
        description: "Grants access to //pos1 and //pos2 commands."
        default: op
      worldstyler.set:
        description: "Grants access to //set command."
        default: op
      worldstyler.replace:
        description: "Grants access to //replace command."
        default: op
      worldstyler.schem:
        description: "Grants access to //schem command."
        default: op
      worldstyler.copy:
        description: "Grants access to //copy command."
        default: op
      worldstyler.paste:
        description: "Grants access to //paste command."
        default: op
      worldstyler.stack:
        description: "Grants access to //stack command."
        default: op
      worldstyler.nice:
        description: "Grants access to //nice command."
        default: op
